config/routes.rb
Rails.application.routes.draw do
  resources :units, only: [:index] do
    collection do
      post :etl
    end
  end

  root to: 'units#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :area, :description, :name, :price, :uom,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.order(name: :asc).decorate
  end

  def etl
    Dir['data/csv/*.csv'].each{ |csv_file| UnitsCsvProcessorWorker.perform_async(csv_file) }
    Dir['data/json/*_units.json'].each{ |json_file| UnitsJsonProcessorWorker.perform_async(json_file) }
    Dir['data/json/*unit_groups.json'].each{ |json_file| UnitGroupsJsonProcessorWorker.perform_async(json_file) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EtlStarterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/units/_import_files.html.haml
= form_tag(etl_units_path) do
  = button_tag type: :submit, class: 'btn waves-effect waves-light' do
    Import files

app/views/units/etl.html.haml
%h2 Data ETL will be ready in a moment

%p.flow-text
  The files are being processed by magic elves, it will take them a few seconds to finish. With lots of luck,
  they will be finished by the time you end reading this text.

.center-align
  <iframe src="https://giphy.com/embed/3ofT5SAruPuAqHEQNy" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>

%p.flow-text
  Go to the #{link_to 'Unit listing', units_path} page. If the data is not there, reload it in a few more seconds.

app/views/units/index.html.haml
%h1 Units

%table.responsive-table
  %thead
    %th Name
    %th Description
    %th Area
    %th Price
  %tfoot
    - unless @units.empty?
      %tr
        %td.center-align{colspan: 4}
          %strong Units displayed:
          = @units.size
      %tr
        %td{colspan: 4}= render partial: 'import_files'


  %tbody
    - if @units.empty?
      %tr
        %td.center-align{colspan: 4}
          %strong No units imported yet, push the 'Import files' button.
          %br
          %br
          = render partial: 'import_files'

    - @units.each do |unit|
      %tr
        %td= unit.name
        %td= unit.description
        %td= unit.area
        %td= unit.price